# Generated by Django 2.0.2 on 2018-03-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='request_to_reset_pass',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
