# Generated by Django 2.0.2 on 2018-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_member_request_to_reset_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reset_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
